ExampleExampleBundle:
    resource: "@ExampleExampleBundle/Resources/config/routing.yml"
    prefix:   /example

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
